Web/CarShop.Web/Controllers/CarsController.cs
namespace CarShop.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using CarShop.Data.Models;
    using CarShop.Services.Data;
    using CarShop.Web.ViewModels.Cars;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class CarsController : Controller
    {
        private readonly ICarService carService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;

        public CarsController(ICarService carService, UserManager<ApplicationUser> userManager, IWebHostEnvironment environment)
        {
            this.carService = carService;
            this.userManager = userManager;
            this.environment = environment;
        }

        public UserManager<ApplicationUser> UserManager { get; }

        [Authorize]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateCarViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.carService.CreateAsync(input, user.Id, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }

            this.TempData["SuccsessfulCarPostCreate"] = "You sucsessfully create car post!";
            return this.RedirectToAction("MyProfile", "Profiles", new { area = string.Empty });
        }

        public IActionResult All(int id = 1)
        {
            const int itemsPerPage = 9;
            var viewModel = new CarListViewModel()
            {
                PageNumber = id,
                Cars = this.carService.GetAll(id, 9),
                CarCount = this.carService.GetCount(),
                ItemsPerPage = itemsPerPage,
            };
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var car = this.carService.GetById<ByIdCarViewModel>(id);
            return this.View(car);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await this.carService.DeleteAsync(id);
            this.TempData["SuccsessfulDeleteCarPost"] = "Your succsesfully delete your post!";
            return this.RedirectToAction(nameof(this.All));
        }
    }
}

Web/CarShop.Web/Controllers/CommentsController.cs
namespace CarShop.Web.Controllers
{
    using System.Threading.Tasks;

    using CarShop.Data.Models;
    using CarShop.Services.Data;
    using CarShop.Web.ViewModels.Comments;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class CommentsController : Controller
    {
        private readonly ICommentService commentService;
        private readonly UserManager<ApplicationUser> userManager;

        public CommentsController(
            ICommentService commentService,
            UserManager<ApplicationUser> userManager)
        {
            this.commentService = commentService;
            this.userManager = userManager;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CommentCreateInputModel input)
        {
            var parentId =
                input.ParentId == 0 ?
                    (int?)null :
                    input.ParentId;

            if (parentId.HasValue)
            {
                if (!this.commentService.IsInCarId(parentId.Value, input.CarId))
                {
                    return this.BadRequest();
                }
            }

            var userId = this.userManager.GetUserId(this.User);

            await this.commentService.Create(input.CarId, userId, input.Content);
            return this.RedirectToAction("ById", "Cars", new { id = input.CarId });
        }
    }
}

Web/CarShop.Web/Controllers/CreditsController.cs
namespace CarShop.Web.Controllers
{
    using System.Threading.Tasks;

    using CarShop.Data.Models;
    using CarShop.Services.Data;

    using CarShop.Web.ViewModels.Credits;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class CreditsController : Controller
    {
        private readonly ICreditService creditService;
        private readonly UserManager<ApplicationUser> userManager;

        public CreditsController(ICreditService creditService, UserManager<ApplicationUser> userManager)
        {
            this.creditService = creditService;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult Create()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateCreditViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var user = await this.userManager.GetUserAsync(this.User);
            await this.creditService.CreateAsync(input, user.Id);

            return this.RedirectToAction($"ById");
        }

        [Authorize]
        public IActionResult ById(int id)
        {
            var credit = this.creditService.GetById<CreditByIdViewModel>(id);
            
            return this.View(credit);
        }
    }
}

Web/CarShop.Web/Views/Cars/All.cshtml
@model CarShop.Web.ViewModels.Cars.CarListViewModel
@{
    this.ViewData["Title"] = "All cars";
}
@if (this.TempData["SuccsessfulDeleteCarPost"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>@this.TempData["SuccsessfulDeleteCarPost"]</strong> You can add new car post from <a asp-controller="Cars" asp-action="Create" class="link-primary">HERE</a><a></a>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<h1>@this.ViewData["Title"]</h1>
<hr />
<div class="row">
    @foreach (var car in Model.Cars)
    {
        <div class="card col-md-4" style="width: 18rem">
            <img src="@car.ImageUrl" class="card-img-top" style="padding-top:10px" alt="Car picture: @car.MarkName">
            <div class="card-body">
                <h5 class="card-title"><strong>@car.MarkName</strong></h5>
                <span><strong>@car.Price BGN</strong></span>
                <span>@car.RegionName</span>
                <span>@car.Milage Km</span>
                <hr>
                <p class="card-text">@car.Description.Substring(0, 85)...</p>
                <a asp-action="ById" asp-route-id="@car.Id" class="btn btn-primary">Show more</a>
            </div>
        </div>
    }
</div>
<hr />
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) {
        <text>disabled</text>
 }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 4; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only"></span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 4; i++)
        {
            if (i <= Model.PageCount)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) {
        <text>disabled</text>
 }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>

Web/CarShop.Web/Views/Cars/ById.cshtml
@model CarShop.Web.ViewModels.Cars.ByIdCarViewModel
@{
    this.ViewData["Title"] = "Car for sale";
}
<h1>@this.ViewData["Title"] @Model.MarkName</h1>
<hr>
<span><strong>Created on: &#128467; Date: </strong> @Model.CreatedOn.ToShortDateString() <strong>&#128346; Time:  </strong> @Model.CreatedOn.ToShortTimeString() </span>

<button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#DeleteCar">Delete</button> 
<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#EditCar">Edit</button>
<form asp-action="Delete" asp-route-id="@Model.Id" id="DeleteCheckModal"></form>
<form asp-action="Edit" asp-route-id="@Model.Id" id="EditCheckModal"></form>
<hr>
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="@Model.ImageUrl" class="d-block w-100" alt="...">
        </div>
    </div>
</div>

<hr>
<div class="col-md-4">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th scope="col"><strong>Parameter</strong></th>
                <th scope="col"><strong>Data</strong></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Mark:</td>
                <td>@Model.MarkName</td>
            </tr>
            <tr>
                <td>Region:</td>
                <td>@Model.RegionName</td>
            </tr>
            <tr>
                <td>Milage:</td>
                <td>@Model.Milage</td>
            </tr>
            <tr>
                <td>Year:</td>
                <td>@Model.Year</td>
            </tr>
            <tr>
                <td>Price:</td>
                <td>@Model.Price BGN</td>
            </tr>
            <tr>
                <td>Engine:</td>
                <td>@Model.EngineType</td>
            </tr>
            <tr>
                <td>Transmission:</td>
                <td>@Model.TransmissionType</td>
            </tr>
        </tbody>
    </table>
</div>
<div class="accordion" id="accordionDescription">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                <strong>Description:</strong>
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionDescription">
            <div class="accordion-body">
                @Model.Description
            </div>
        </div>
    </div>
</div>
<hr>
<div class="col-md-4">
    <ul class="list-group">
        <li class="list-group-item active" aria-current="true">Contacts of the saler:</li>
        <li class="list-group-item">Name: @Model.CreatedByUserUserName</li>
        <li class="list-group-item">Email: <a href=mailto:"@Model.Email">@Model.Email</a></li>
        <li class="list-group-item">Telefon number: <button class="btn btn-primary btn-sm" onclick="showAndHide()">Show number</button> <a style="display:none" id="TelNum" href="tel:@Model.TelephoneNumber">@Model.TelephoneNumber</a></li>
    </ul>
</div>
<hr>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    I don't have enough money
</button>
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Hello brokie, we are glad to inform you that you can own this junk with our 36 month leasing!</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Now you can have this <strong>@Model.MarkName</strong> for only <strong> @Math.Round(Model.Price/36) </strong> BGN a month for 3 years! <br> Wanna get credit?
            </div>
            <hr>
            <div>
                <img src="https://pbs.twimg.com/media/EViwYl8WoAIzYL3.jpg" alt="Kermith thinking in depression" width="300">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No thanks</button>
                <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Create","Credits")'">Hell Yeah</button>
            </div>
        </div>
    </div>
</div>
<!-- Printing-->
<button type="button" class="btn btn-info" onclick="window.print()">Print this page</button>
<!-- Modal DeleteCar for confirmation window -->
<div class="modal" tabindex="-1" id="DeleteCar">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Do you want to delete this @Model.MarkName?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" onclick="DeleteCheckModal.submit()">Yes</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal EditPost for confirmation window ------------------TODO------->
<div class="modal fade" id="modalDelete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Post</h5>
                <hr>
            </div>
            <div class="modal-body">
                Do you want to delete "" post?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" onclick="deletePost.submit()">Delete Post &#10060</button>
            </div>
        </div>
    </div>
</div>
<!-- COMMENTS SECTION -->
<hr>
@if (Model.Comments.Count() < 1)
{
    <span><strong>No comments yet:</strong></span>
}
else
{
    <span><strong>Comments: @Model.Comments.Count()</strong></span>
}

<div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Comments" asp-action="Create" method="post" id="AddCommentForm" style="display: block">
        <input type="hidden" name="CarId" value="@Model.Id" />
        <div>
            <label for="Content"></label>
            <textarea name="Content" id="Content" class="form-control" placeholder="Write your comment here."></textarea>
        </div>
        <hr>
        <div>
            <input type="submit" class="btn btn-primary" value="Add comment" />
        </div>
    </form>
</div>
<hr>

@foreach (var comment in Model.Comments.ToList().OrderByDescending(x => x.CreatedOn))
{
    <div class="card">
        <div class="card-header" style="background-color:cadetblue">
            <strong>@comment.UserUserName</strong>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>@comment.Content</p>
                <footer class="blockquote-footer">@comment.CreatedOn.ToShortDateString() | @comment.CreatedOn.ToShortTimeString()</footer>
            </blockquote>
            <button type="button" class="btn btn-primary">Reply to this comment</button>
        </div>
        <hr>
    </div>
}

@section Scripts {
    <script>
        function showAddCommentForm(parentId) {
            $("#AddCommentForm").show();
            $([document.documentElement, document.body]).animate({
                scrollTop: $("#AddCommentForm").offset().top
            }, 1000);
        }

        function showAndHide() {
            var x = document.getElementById("TelNum");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }
    </script>
}

Web/CarShop.Web/Views/Cars/Create.cshtml
@model CarShop.Web.ViewModels.Cars.CreateCarViewModel
@{
    this.ViewData["Title"] = "Add new car";
}
<h1>Add new car post!</h1>
<form method="post" class="col-md-4 offset-4" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="MarkId">Mark</label>
        <select asp-for="MarkId" class="form-control">
            <option value="1">Audi</option>
        </select>
        <span asp-validation-for="MarkId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control" rows="3"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TelephoneNumber"></label>
        <input asp-for="TelephoneNumber" class="form-control" />
        <span asp-validation-for="TelephoneNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Images"></label>
        <input asp-for="Images" class="form-control" accept="image/*" id="imgInp" />
        <span asp-validation-for="Images" class="text-danger"></span>
    </div>
    <br>
        <img id="imgPreview" src="#" alt=" " width="250" />
    <br>
    <div class="form-group">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="IsUsed">Used</label>
        <input type="checkbox" asp-for="IsUsed" />
        <span asp-validation-for="IsUsed" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EngineId"></label>
        <select asp-for="EngineId" class="form-control">
            <option value="1">Disel</option>
            <option value="2">Gasoline</option>
            <option value="3">Electric</option>
            <option value="4">Hibrid</option>
        </select>
        <span asp-validation-for="EngineId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TransmissionId"></label>
        <select asp-for="TransmissionId" class="form-control">
            <option value="1">Manual gearbox</option>
            <option value="2">Automatic gearbox</option>
            <option value="3">Semi-automatic gearbox</option>
        </select>
        <span asp-validation-for="TransmissionId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="RegionId"></label>
        <select asp-for="RegionId" class="form-control">
            <option value="1">Blagoevgrad</option>
        </select>
        <span asp-validation-for="RegionId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Milage"></label>
        <input asp-for="Milage" class="form-control" />
        <span asp-validation-for="Milage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Year"></label>
        <input asp-for="Year" class="form-control" />
        <span asp-validation-for="Year" class="text-danger"></span>
    </div>
    <hr />
    <input type="submit" as class="btn btn-primary" />
</form>

<script>
    imgInp.onchange = evt => {
        const [file] = imgInp.files
        if (file) {
            imgPreview.src = URL.createObjectURL(file)
        }
    }
</script>