Web/CarShop.Web/Areas/Administration/Controllers/MarksController.cs
namespace CarShop.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using CarShop.Data.Common.Repositories;
    using CarShop.Data.Models;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    [Area("Administration")]
    public class MarksController : AdministrationController
    {
        private readonly IDeletableEntityRepository<Mark> marksRepository;

        public MarksController(IDeletableEntityRepository<Mark> marksRepository)
        {
            this.marksRepository = marksRepository;
        }

        // GET: Administration/Marks
        public async Task<IActionResult> Index()
        {
              return this.View(await this.marksRepository.AllWithDeleted().ToListAsync());
        }

        // GET: Administration/Marks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || this.marksRepository.All() == null)
            {
                return this.NotFound();
            }

            var mark = await this.marksRepository.All()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mark == null)
            {
                return this.NotFound();
            }

            return this.View(mark);
        }

        // GET: Administration/Marks/Create
        public IActionResult Create()
        {
            return this.View();
        }

        // POST: Administration/Marks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Mark mark)
        {
            if (this.ModelState.IsValid)
            {
                await this.marksRepository.AddAsync(mark);
                await this.marksRepository.SaveChangesAsync();
                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(mark);
        }

        // GET: Administration/Marks/Edit/5
       

        // POST: Administration/Marks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Mark mark)
        {
            if (id != mark.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.marksRepository.Update(mark);
                    await this.marksRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.MarkExists(mark.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(mark);
        }

        // GET: Administration/Marks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || this.marksRepository.All() == null)
            {
                return this.NotFound();
            }

            var mark = await this.marksRepository.All()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mark == null)
            {
                return this.NotFound();
            }

            return this.View(mark);
        }

        // POST: Administration/Marks/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (this.marksRepository.All() == null)
            {
                return this.Problem("Entity set 'ApplicationDbContext.Marks'  is null.");
            }

            var mark = this.marksRepository.All().FirstOrDefault(m => m.Id == id);
            if (mark != null)
            {
                this.marksRepository.Delete(mark);
            }

            await this.marksRepository.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.Index));
        }

        private bool MarkExists(int id)
        {
          return this.marksRepository.All().Any(e => e.Id == id);
        }
    }
}

Web/CarShop.Web/Controllers/CarsController.cs
namespace CarShop.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using CarShop.Data.Models;
    using CarShop.Services.Data;
    using CarShop.Web.ViewModels.Cars;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class CarsController : Controller
    {
        private readonly ICarService carService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;

        public CarsController(ICarService carService, UserManager<ApplicationUser> userManager, IWebHostEnvironment environment)
        {
            this.carService = carService;
            this.userManager = userManager;
            this.environment = environment;
        }

        public UserManager<ApplicationUser> UserManager { get; }

        [Authorize]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateCarViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.carService.CreateAsync(input, user.Id, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }

            this.TempData["SuccsessfulCarPostCreate"] = "You sucsessfully create car post!";
            return this.RedirectToAction("MyProfile", "Profiles", new { area = string.Empty });
        }

        public IActionResult All(int id = 1)
        {
            const int itemsPerPage = 9;
            var viewModel = new CarListViewModel()
            {
                PageNumber = id,
                Cars = this.carService.GetAll(id, 9),
                CarCount = this.carService.GetCount(),
                ItemsPerPage = itemsPerPage,
            };
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var car = this.carService.GetById<ByIdCarViewModel>(id);
            return this.View(car);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await this.carService.DeleteAsync(id);
            this.TempData["SuccsessfulDeleteCarPost"] = "Your succsesfully delete your post!";
            return this.RedirectToAction(nameof(this.All));
        }
    }
}

Web/CarShop.Web/Controllers/CreditsController.cs
namespace CarShop.Web.Controllers
{
    using System.Threading.Tasks;

    using CarShop.Data.Models;
    using CarShop.Services.Data;

    using CarShop.Web.ViewModels.Credits;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class CreditsController : Controller
    {
        private readonly ICreditService creditService;
        private readonly UserManager<ApplicationUser> userManager;

        public CreditsController(ICreditService creditService, UserManager<ApplicationUser> userManager)
        {
            this.creditService = creditService;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult Create()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateCreditViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var user = await this.userManager.GetUserAsync(this.User);
            await this.creditService.CreateAsync(input, user.Id);

            return this.RedirectToAction($"ById");
        }

        [Authorize]
        public IActionResult ById(int id)
        {
            var credit = this.creditService.GetById<CreditByIdViewModel>(id);
            
            return this.View(credit);
        }
    }
}

Web/CarShop.Web/Controllers/SearchController.cs
namespace CarShop.Web.Controllers
{
    using CarShop.Services.Data;
    using CarShop.Web.ViewModels.Cars;
    using CarShop.Web.ViewModels.Search;
    using Microsoft.AspNetCore.Mvc;

    public class SearchController : BaseController
    {
        private readonly ICarService carService;

        public SearchController(ICarService carService)
        {
            this.carService = carService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        [HttpGet]
        public IActionResult List(SearchListInputModel input)
        {
            var cars = new CarListViewModel()
            {
                Cars = this.carService.GetAllSearch(input.MinPrice, input.MaxPrice, input.EngineId),
            };

            return this.View(cars);
        }
    }
}

Web/CarShop.Web/Views/Shared/_Layout.cshtml
@using CarShop.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Create">Add car</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="All">All</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Credits" asp-action="Create">Credit</a>
                        </li>
                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administration" asp-controller="Marks" asp-action="Index">Marks Admin</a>
                            </li>
                        }
                         <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="Profiles" asp-action="MyProfile">MyProfile</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marketing" asp-action="RedirectTo">Marketing</a>
                        </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>